os: linux
dist: focal
language: go
go:
- 1.17.x
env:
  global:
  - CI_CONFIG_DIR=build/ci/.env
  - BRANCH_NAME=$TRAVIS_BRANCH
  - CI_STAGE=$TRAVIS_BUILD_STAGE_NAME

branches:
  only:
    - master
    - taufiq-ismail

script: bash build/ci/ci.sh $CI_STAGE $CMD_PATH $BRANCH_NAME

jobs:
  include:
    # TEST
    - stage: "test"
      name: "Run Unit Testing"
      if: type = pull_request AND (commit_message !~ /skip_test/)
    
    # BUILD BASE IMAGE
    - stage: "build-base"
      name: "base_image"
      if: type = push AND (commit_message =~ /\(build_base\)/ OR commit_message =~ /build_all/)
      
    # ADD YOUR SERVICE OR CONSOLE HERE
    - stage: "build"
      name: "taufiq-ismail"
      env: CMD_PATH=cmd/console1
      if: type = push AND (commit_message =~ /\(console1\)/ OR commit_message =~ /build_all/)
    - name: "taufiq-ismail"
      env: CMD_PATH=cmd/service/taufiq-ismail
      if: type = push AND (commit_message =~ /\(taufiq-ismail\)/ OR commit_message =~ /build_all/)